server:
  port: 8012
eureka:
  client:
    serviceUrl:
      defaultZone: http://ztp:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: microservice-movie-ribbon