security:
  basic:
    enabled: true
  user:
    name: ztp
    password: 123456
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://ztp:123456@localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
